"""
FastAPI REST server for dots.tts voice cloning.

Loads the model once on startup, then exposes a single POST endpoint for
synthesis.  Clients send text, a reference audio sample (base64), and the
transcript of that sample.  The server returns the generated audio as
base64-encoded WAV.

Usage:
    uvicorn apps.rest_api.server:app --host 0.0.0.0 --port 8000

Generated by Qwen 3.6 27B Q6
"""

from __future__ import annotations

import base64
import io
import math
import random
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"

# Ensure the project source is on sys.path so `dots_tts` imports resolve.
for import_root in (REPO_ROOT, SRC_ROOT):
    import_root_str = str(import_root)
    if import_root_str not in sys.path:
        sys.path.insert(0, import_root_str)

import soundfile as sf  # noqa: E402
import torch  # noqa: E402
from fastapi import FastAPI, HTTPException  # noqa: E402
from fastapi.responses import HTMLResponse  # noqa: E402
from fastapi.responses import JSONResponse  # noqa: E402
from loguru import logger  # noqa: E402
from pydantic import BaseModel, Field, field_validator  # noqa: E402
from typing_extensions import Literal  # noqa: E402

from dots_tts.runtime import DotsTtsRuntime  # noqa: E402
from dots_tts.utils.util import seed_everything  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# You can specify the huggingface id of the model: "rednote-hilab/dots.tts-soar"
# That will pull it from your local cache, or download it if you don't have it.
#
# Alternatively, you can download it to some local directory,
# and specify the path: "/home/user/my-models/dots.tts-soar/"
MODEL_NAME_OR_PATH = "rednote-hilab/dots.tts-soar"

DEFAULT_PRECISION = "bfloat16"
DEFAULT_GUIDANCE_SCALE = 1.2
DEFAULT_SPEAKER_SCALE = 1.5
DEFAULT_ODE_METHOD = "euler"
SEED_MIN = 1
SEED_MAX = 1000
NUM_STEPS_MIN = 10
NUM_STEPS_MAX = 20

# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------


class SynthesisRequest(BaseModel):
    """A single synthesis request."""

    text: str = Field(..., description="Text to synthesize, e.g. 'Hello there'")
    audio_base64: str = Field(
        ...,
        description=(
            "Reference audio sample (~10 s WAV) encoded as a base64 string. "
            "The server will decode this to a temporary WAV file before synthesis."
        ),
    )
    prompt_text: str = Field(
        ...,
        description=(
            "Exact transcript of the reference audio, e.g. "
            "'Hello, my name is Alice, nice to meet you'."
        ),
    )

    # Optional overrides (defaults are sensible for voice cloning)
    seed: int | None = Field(
        None,
        ge=SEED_MIN,
        le=SEED_MAX,
        description=(
            "Random seed for reproducibility.  If omitted, a random seed "
            f"in [{SEED_MIN}, {SEED_MAX}] is chosen."
        ),
    )
    num_steps: int | None = Field(
        None,
        ge=NUM_STEPS_MIN,
        le=NUM_STEPS_MAX,
        description=(
            "Number of flow-matching sampling steps.  If omitted, a random "
            f"integer in [{NUM_STEPS_MIN}, {NUM_STEPS_MAX}] is chosen."
        ),
    )
    guidance_scale: float = Field(
        DEFAULT_GUIDANCE_SCALE,
        description="Classifier-free guidance scale.",
    )
    speaker_scale: float = Field(
        DEFAULT_SPEAKER_SCALE,
        description="Scale applied to the reference speaker embedding.",
    )
    ode_method: Literal["euler", "midpoint", "rk4"] = Field(
        DEFAULT_ODE_METHOD,
        description="ODE / flow-matching solver method.",
    )
    language: str | None = Field(
        None,
        description="Language tag (e.g. 'EN', 'ZH').  None = auto.",
    )


class SynthesisResponse(BaseModel):
    """The synthesis result."""

    audio_base64: str = Field(
        ...,
        description="Generated WAV audio encoded as a base64 string.",
    )
    sample_rate: int = Field(..., description="Audio sample rate (Hz).")
    seed: int = Field(..., description="Seed used for this generation.")
    num_steps: int = Field(..., description="Number of steps used.")
    fid: str = Field(..., description="Request ID (internal).")
    time_used: float = Field(
        ..., description="Wall-clock generation time in seconds."
    )
    rtf: float | None = Field(
        ...,
        description=(
            "Real-time factor (time / audio duration).  "
            "null when audio duration is zero."
        ),
    )

    @field_validator("rtf", mode="before")
    @classmethod
    def _sanitize_rtf(cls, v: float | None) -> float | None:
        """Replace inf / nan with None so JSON serialization never fails."""
        if v is None:
            return None
        if math.isinf(v) or math.isnan(v):
            return None
        return v

    @field_validator("time_used", mode="before")
    @classmethod
    def _sanitize_time_used(cls, v: float | None) -> float | None:
        """Guard against inf / nan in time_used as well."""
        if v is None:
            return None
        if math.isinf(v) or math.isnan(v):
            return 0.0
        return v


class HealthResponse(BaseModel):
    """Health / readiness check."""

    status: Literal["ok"] = "ok"
    serverType: Literal["dots.tts"] = "dots.tts"
    model: str = MODEL_NAME_OR_PATH


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="dots.tts Voice Cloning API",
    description=(
        "REST API around dots.tts.  Send text + a reference audio sample "
        "and get back cloned speech."
    ),
    version="0.1.0",
)

# ---------------------------------------------------------------------------
# Lazy model loading — loaded on first request (or explicitly via startup).
# ---------------------------------------------------------------------------

_runtime: DotsTtsRuntime | None = None


def _get_runtime() -> DotsTtsRuntime:
    """Return the global runtime, loading it once if necessary."""
    global _runtime
    if _runtime is None:
        logger.info(
            "Loading dots.tts model '{}' (precision={}) ...",
            MODEL_NAME_OR_PATH,
            DEFAULT_PRECISION,
        )
        _runtime = DotsTtsRuntime.from_pretrained(
            MODEL_NAME_OR_PATH,
            precision=DEFAULT_PRECISION,
        )
        logger.info("Model loaded successfully.")
    return _runtime


# ---------------------------------------------------------------------------
# Global exception handler — catches anything that slips past endpoint handlers
# ---------------------------------------------------------------------------


@app.exception_handler(Exception)
async def _unhandled_exception(
    _request, exc: Exception
) -> JSONResponse:
    """Return a meaningful 500 instead of FastAPI's blank ``detail: ''``."""
    logger.error("Unhandled exception: {}", exc, exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": f"Internal server error: {exc}"},
    )


# ---------------------------------------------------------------------------
# Startup / shutdown hooks
# ---------------------------------------------------------------------------


@app.on_event("startup")
def startup() -> None:
    """Pre-load the model so the first request is fast."""
    _get_runtime()


@app.on_event("shutdown")
def shutdown() -> None:
    """Clean up GPU resources."""
    global _runtime
    if _runtime is not None:
        # Release CUDA memory.
        del _runtime.model
        _runtime = None
    torch.cuda.empty_cache()
    logger.info("Model unloaded and CUDA cache cleared.")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@app.get("/", response_class=HTMLResponse, tags=["System"])
def root() -> str:
    """A friendly landing page so browser visitors don't get the auto-generated docs."""
    return """
    <!DOCTYPE html>
    <html>
    <head><title>dots.tts REST API</title></head>
    <body>
        <h1>dots.tts Voice Cloning REST API</h1>
        <p>This server is configured and running. It is a REST API, not a web server.</p>
        <p>Use a REST client like <strong>Postman</strong>, <strong>Insomnia</strong>,
        or <strong>curl</strong> to make requests.</p>
        <ul>
            <li><code>GET /health</code> &mdash; Check server status</li>
            <li><code>POST /synthesize</code> &mdash; Generate cloned speech</li>
        </ul>
    </body>
    </html>
    """


@app.get("/health", response_model=HealthResponse, tags=["System"])
def health() -> HealthResponse:
    """Check whether the server is alive and the model is loaded."""
    model_loaded = _runtime is not None
    if not model_loaded:
        logger.warning("Health check: model not yet loaded.")
    return HealthResponse()


@app.post(
    "/synthesize",
    response_model=SynthesisResponse,
    tags=["Synthesis"],
    summary="Synthesize speech from text + reference audio",
)
def synthesize(req: SynthesisRequest) -> SynthesisResponse:
    """
    Synthesize audio using the provided text and reference audio sample.

    Parameters
    ----------
    req : SynthesisRequest
        - **text**: The text to speak.
        - **audio_base64**: Base64-encoded WAV reference audio.
        - **prompt_text**: Transcript of the reference audio.
        - **seed** (optional): Random seed (1–1000).  Random if omitted.
        - **num_steps** (optional): Sampling steps (10–20).  Random if omitted.
        - **guidance_scale**, **speaker_scale**, **ode_method**, **language**:
          Optional tuning parameters.

    Returns
    -------
    SynthesisResponse
        Base64-encoded WAV audio, sample rate, seed, steps, timing metrics.
    """
    runtime = _get_runtime()

    # Resolve randomised parameters.
    seed = req.seed if req.seed is not None else random.randint(SEED_MIN, SEED_MAX)
    num_steps = (
        req.num_steps
        if req.num_steps is not None
        else random.randint(NUM_STEPS_MIN, NUM_STEPS_MAX)
    )

    logger.info(
        "Synthesizing: seed={}, steps={}, text_len={}, guidance={:.1f}, "
        "speaker_scale={:.1f}, ode={}, lang={}",
        seed,
        num_steps,
        len(req.text),
        req.guidance_scale,
        req.speaker_scale,
        req.ode_method,
        req.language,
    )

    # Set the random seed for reproducibility.
    seed_everything(seed)

    # Decode the base64 audio and write to a temporary file.
    try:
        raw_audio = base64.b64decode(req.audio_base64)
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid base64 audio: {exc}")

    prompt_audio_path = _write_temp_wav(raw_audio)

    try:
        # Call the runtime.
        result = runtime.generate(
            text=req.text,
            prompt_audio_path=prompt_audio_path,
            prompt_text=req.prompt_text,
            ode_method=req.ode_method,
            num_steps=num_steps,
            guidance_scale=req.guidance_scale,
            speaker_scale=req.speaker_scale,
            language=req.language,
        )

        # Encode the output WAV to base64.
        audio_bytes = _tensor_to_wav_bytes(
            result["audio"], result["sample_rate"]
        )
        audio_b64 = base64.b64encode(audio_bytes).decode("ascii")

        return SynthesisResponse(
            audio_base64=audio_b64,
            sample_rate=result["sample_rate"],
            seed=seed,
            num_steps=num_steps,
            fid=result["fid"],
            time_used=result["time_used"],
            rtf=result["rtf"],
        )

    except Exception as exc:
        logger.error("Synthesis failed: {}", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))
    finally:
        # Clean up the temporary prompt audio file.
        _cleanup_temp(prompt_audio_path)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_TEMP_AUDIO_DIR = Path("/tmp/dots_tts_rest_api")
_TEMP_AUDIO_DIR.mkdir(exist_ok=True)


def _write_temp_wav(raw_bytes: bytes) -> str:
    """
    Write raw audio bytes to a temporary WAV file.

    The input is expected to be a valid WAV file (just bytes).  We write it
    directly to disk because the runtime expects a file path.
    """
    import uuid

    path = _TEMP_AUDIO_DIR / f"{uuid.uuid4().hex}.wav"
    path.write_bytes(raw_bytes)
    logger.debug("Wrote temporary prompt audio: {}", path)
    return str(path)


def _cleanup_temp(path: str) -> None:
    """Remove a temporary audio file if it exists."""
    try:
        Path(path).unlink(missing_ok=True)
    except OSError:
        pass


def _tensor_to_wav_bytes(
    audio_tensor: torch.Tensor, sample_rate: int
) -> bytes:
    """
    Convert a torch audio tensor to WAV-encoded bytes.

    Parameters
    ----------
    audio_tensor : torch.Tensor
        Shape (1, samples), dtype float32 in [-1, 1].
    sample_rate : int
        Sample rate in Hz.

    Returns
    -------
    bytes
        Raw WAV file bytes.
    """
    buffer = io.BytesIO()
    sf.write(
        buffer,
        audio_tensor.float().cpu().squeeze().numpy(),
        sample_rate,
        format="WAV",
        subtype="PCM_16",
    )
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# Main (for running directly: python -m apps.rest_api.server)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    logger.info("Starting dots.tts REST API server on 0.0.0.0:8000")
    uvicorn.run(
        "apps.rest_api.server:app",
        host="0.0.0.0",
        port=8000,
        log_level="info",
    )
